# Generated by Django 5.1.2 on 2024-10-29 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMaterialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=32)),
                ('material_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.materialmodel')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.productmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=32)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.productmodel')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remainder', models.DecimalField(decimal_places=2, max_digits=32)),
                ('free', models.DecimalField(decimal_places=2, max_digits=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=32)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('material_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.materialmodel')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
